version: "3.7"
services:
  data-collector:
    build:
      context: ./backend
      dockerfile: kb-data-collector.Dockerfile
    image: kb-data-collector
    environment:
      PORT: 8080
      NODE_ENV: dev
      CORS_ORIGINS: localhost
      MONGO_ADDRESS: mongodb://mongo:27017/dev
      MQ_ADDRESS: amqp://dev:dev@rabbitmq:5672
      MQ_CONSUMER_QUEUE_NAME: collecting-scenario
      MQ_DATA_COLLECTION_NOTIFICATIONS_QUEUE_NAME: data-collection-notifications
      MQ_USER_NOTIFICATIONS_QUEUE_NAME: data-to-process
    volumes:
      - ./scraping-results:/usr/src/app/dist/apps/data-collector/results
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 38080:8080
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "main"]

  search-queue-manager:
    build:
      context: ./backend
      dockerfile: kb-search-queue-manager.Dockerfile
    image: kb-search-queue-manager
    environment:
      PORT: 8080
      NODE_ENV: dev
      CORS_ORIGINS: localhost
      MONGO_ADDRESS: mongodb://mongo:27017/dev
      MQ_ADDRESS: amqp://dev:dev@rabbitmq:5672
      MQ_CONSUMER_QUEUE_NAME: data-collection-notifications
      COLLECTING_SCENARIO_QUEUE_NAME: collecting-scenario
      MQ_USER_NOTIFICATIONS_QUEUE_NAME: user-notifications
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    ports:
    - 38081:8080
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "main"]
#
#  user-service:
#    build:
#      context: ./backend
#      dockerfile: backend/kb-user-service.Dockerfile
#    image: kb-user-service
#    volumes:
#      - ./tools/wait-for-it.sh:/wait-for-it.sh
#    ports:
#    - 38082:8080
#    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "main"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    volumes:
    - ./backend/mq/rmq-definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 15672:15672
      - 5672:5672

  mongo:
    image: mongo
    ports:
      - 27017:27017
