version: "3.7"
services:
  data-collector:
    build:
      context: ./backend
      dockerfile: backend/kb-data-collector.Dockerfile
    image: kb-data-collector
    environment:
      NODE_ENV: dev
      PUPPETEER_HEADLESS_SCRAPING: "true"
      PUPPETEER_EXECUTABLE_PATH: google-chrome-unstable
      SAVE_RESULTS_AS_JSON_AND_TAKE_SCREENSHOTS_ON_ERROR: "true"
    volumes:
      - ./scraping-results:/usr/src/app/results
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    ports:
      - 38080:8080

  search-request-manager:
    build:
      context: ./backend
      dockerfile: backend/kb-search-request-manager.Dockerfile
    image: kb-search-request-manager
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    ports:
    - 38081:8080
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "main"]

  user-service:
    build:
      context: ./backend
      dockerfile: backend/kb-user-service.Dockerfile
    image: kb-user-service
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    ports:
    - 38082:8080
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "main"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    volumes:
    - ./backend/mq/rmq-definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 15672:15672
      - 5672:5672
